services:
  auth-service:
    image: mortenstaunstrup/authservice-image:latest
    expose:
      - "8080"
    networks:
      - fitlife
    environment:
      - VAULT_URL=https://vault:8201/
  
  user-service:
    image: mortenstaunstrup/userservice-image:latest
    expose:
      - "8080"
    networks:
      - fitlife
    environment:
      - AUTHSERVICE_URL=http://nginx:4000/authservices/
      - VAULT_URL=https://vault:8201/
  
  membership-service:
    image: mortenstaunstrup/membershipservice-image:latest
    expose:
      - "8080"
    networks:
      - fitlife
    environment:
      - AUTHSERVICE_URL=http://nginx:4000/authservices/
      - VAULT_URL=https://vault:8201/
  session-service:
    image: umutnaz/sessionservice-image:latest
    expose:
      - "8080"
    networks:
      - fitlife
    environment:
      - AUTHSERVICE_URL=http://nginx:4000/authservices/
      - VAULT_URL=https://vault:8201/
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - user-service
      - membership-service
      - session-service
    ports:
      - "4000:4000"
    networks:
      - fitlife


networks:
  fitlife:
    external: true