user nginx;

events {
    worker_connections 1000;
}
http {

    upstream authservices {
        server auth-service:8080;
    }


    server {
            listen 4000;
           
            location /authservices/ {
                proxy_pass http://authservices/;
            }

    }
}